# _config.yml (cleaned and production-ready)
title: Jonathan Thomas
email: jonathanthomas83@gmail.com
description: >
  Jonathan Thomas is a UX designer based in South Wales.
baseurl: "" # e.g. /blog
url: "https://jonathanpthomas.com"
github_username: jonathanthomas83

remote_theme: jonathanthomas83/jekyll-govuk

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      layout: default

collections:
  case-studies:
    output: true
    permalink: /case-studies/:path/
    defaults:
      values:
        layout: portfolio-page

sass:
  style: compressed

include:
  - _sass

exclude:
  - keep/

custom_site_logo_width: true

header_links:
  - name: "Home"
    url: "/"
  - name: "Case studies"
    url: "/case-studies/"
