# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonathan Thomas
email: info@jonathanpthomas.com
description: > # this means to ignore newlines until "baseurl:"
  Jonathan Thomas is a UX designer based in South Wales.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jonthomas83
github_username:  jonathanthomas83

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
