- period: 2019
  description: Scrum Master

- period: 2014 – 2017
  description: >
    GDS content design, Lean UX, Coaching, Usability,
    Prototyping, WAI-ARIA, Agile

- period: 2014
  description: Certified Responsive Web Design Specialist

- period: 2011 – 2014
  description: HTML5, CSS3, Mobile Web Design, jQuery, XML, PHP

- period: 2007
  description: |
    1st Class BSc, Interactive New Media Technologies<br />
    at University of Glamorgan